spring:
  datasource:
    url: jdbc:postgresql://wallet_db:5432/wallet_db
    username: andrey
    password: 1384
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
      javax.persistence.transactionType: RESOURCE_LOCAL

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml